// Code generated by MockGen. DO NOT EDIT.
// Source: ../service/appointment_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	models "github.com/ViniciusBoroto/cabeleleila_leila/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAppointmentService is a mock of AppointmentService interface.
type MockAppointmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentServiceMockRecorder
}

// MockAppointmentServiceMockRecorder is the mock recorder for MockAppointmentService.
type MockAppointmentServiceMockRecorder struct {
	mock *MockAppointmentService
}

// NewMockAppointmentService creates a new mock instance.
func NewMockAppointmentService(ctrl *gomock.Controller) *MockAppointmentService {
	mock := &MockAppointmentService{ctrl: ctrl}
	mock.recorder = &MockAppointmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentService) EXPECT() *MockAppointmentServiceMockRecorder {
	return m.recorder
}

// ConfirmAppointment mocks base method.
func (m *MockAppointmentService) ConfirmAppointment(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAppointment", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmAppointment indicates an expected call of ConfirmAppointment.
func (mr *MockAppointmentServiceMockRecorder) ConfirmAppointment(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAppointment", reflect.TypeOf((*MockAppointmentService)(nil).ConfirmAppointment), id)
}

// CreateAppointment mocks base method.
func (m *MockAppointmentService) CreateAppointment(customerID uint, services []models.Service, date time.Time) (models.Appointment, *models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", customerID, services, date)
	ret0, _ := ret[0].(models.Appointment)
	ret1, _ := ret[1].(*models.Appointment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockAppointmentServiceMockRecorder) CreateAppointment(customerID, services, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockAppointmentService)(nil).CreateAppointment), customerID, services, date)
}

// GetWeeklyPerformance mocks base method.
func (m *MockAppointmentService) GetWeeklyPerformance() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeeklyPerformance")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWeeklyPerformance indicates an expected call of GetWeeklyPerformance.
func (mr *MockAppointmentServiceMockRecorder) GetWeeklyPerformance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeeklyPerformance", reflect.TypeOf((*MockAppointmentService)(nil).GetWeeklyPerformance))
}

// ListAll mocks base method.
func (m *MockAppointmentService) ListAll() ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockAppointmentServiceMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockAppointmentService)(nil).ListAll))
}

// ListHistory mocks base method.
func (m *MockAppointmentService) ListHistory(start, end time.Time) ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistory", start, end)
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHistory indicates an expected call of ListHistory.
func (mr *MockAppointmentServiceMockRecorder) ListHistory(start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistory", reflect.TypeOf((*MockAppointmentService)(nil).ListHistory), start, end)
}

// UpdateAppointment mocks base method.
func (m *MockAppointmentService) UpdateAppointment(id uint, newAp models.Appointment) (models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", id, newAp)
	ret0, _ := ret[0].(models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockAppointmentServiceMockRecorder) UpdateAppointment(id, newAp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockAppointmentService)(nil).UpdateAppointment), id, newAp)
}
