// Code generated by MockGen. DO NOT EDIT.
// Source: ../service/service_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/ViniciusBoroto/cabeleleila_leila/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceService is a mock of ServiceService interface.
type MockServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceServiceMockRecorder
}

// MockServiceServiceMockRecorder is the mock recorder for MockServiceService.
type MockServiceServiceMockRecorder struct {
	mock *MockServiceService
}

// NewMockServiceService creates a new mock instance.
func NewMockServiceService(ctrl *gomock.Controller) *MockServiceService {
	mock := &MockServiceService{ctrl: ctrl}
	mock.recorder = &MockServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceService) EXPECT() *MockServiceServiceMockRecorder {
	return m.recorder
}

// CreateService mocks base method.
func (m *MockServiceService) CreateService(service models.Service) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", service)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockServiceServiceMockRecorder) CreateService(service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockServiceService)(nil).CreateService), service)
}

// DeleteService mocks base method.
func (m *MockServiceService) DeleteService(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteService", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockServiceServiceMockRecorder) DeleteService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockServiceService)(nil).DeleteService), id)
}

// GetService mocks base method.
func (m *MockServiceService) GetService(id uint) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", id)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockServiceServiceMockRecorder) GetService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockServiceService)(nil).GetService), id)
}

// ListServices mocks base method.
func (m *MockServiceService) ListServices() ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices")
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockServiceServiceMockRecorder) ListServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockServiceService)(nil).ListServices))
}

// UpdateService mocks base method.
func (m *MockServiceService) UpdateService(service models.Service) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", service)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockServiceServiceMockRecorder) UpdateService(service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockServiceService)(nil).UpdateService), service)
}
