// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/appointment_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	models "github.com/ViniciusBoroto/cabeleleila_leila/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAppointmentRepository is a mock of AppointmentRepository interface.
type MockAppointmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentRepositoryMockRecorder
}

// MockAppointmentRepositoryMockRecorder is the mock recorder for MockAppointmentRepository.
type MockAppointmentRepositoryMockRecorder struct {
	mock *MockAppointmentRepository
}

// NewMockAppointmentRepository creates a new mock instance.
func NewMockAppointmentRepository(ctrl *gomock.Controller) *MockAppointmentRepository {
	mock := &MockAppointmentRepository{ctrl: ctrl}
	mock.recorder = &MockAppointmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentRepository) EXPECT() *MockAppointmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppointmentRepository) Create(ap models.Appointment) (models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ap)
	ret0, _ := ret[0].(models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppointmentRepositoryMockRecorder) Create(ap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppointmentRepository)(nil).Create), ap)
}

// FindByID mocks base method.
func (m *MockAppointmentRepository) FindByID(id uint) (models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAppointmentRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAppointmentRepository)(nil).FindByID), id)
}

// FindUserAppointmentsInWeek mocks base method.
func (m *MockAppointmentRepository) FindUserAppointmentsInWeek(userID uint, weekStart, weekEnd time.Time) ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserAppointmentsInWeek", userID, weekStart, weekEnd)
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserAppointmentsInWeek indicates an expected call of FindUserAppointmentsInWeek.
func (mr *MockAppointmentRepositoryMockRecorder) FindUserAppointmentsInWeek(userID, weekStart, weekEnd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserAppointmentsInWeek", reflect.TypeOf((*MockAppointmentRepository)(nil).FindUserAppointmentsInWeek), userID, weekStart, weekEnd)
}

// ListAll mocks base method.
func (m *MockAppointmentRepository) ListAll() ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockAppointmentRepositoryMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockAppointmentRepository)(nil).ListAll))
}

// ListByPeriod mocks base method.
func (m *MockAppointmentRepository) ListByPeriod(start, end time.Time) ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPeriod", start, end)
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPeriod indicates an expected call of ListByPeriod.
func (mr *MockAppointmentRepositoryMockRecorder) ListByPeriod(start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPeriod", reflect.TypeOf((*MockAppointmentRepository)(nil).ListByPeriod), start, end)
}

func (m *MockAppointmentRepository) ListByPeriodAndUser(userID uint, start, end time.Time) ([]models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPeriod", userID, start, end)
	ret0, _ := ret[0].([]models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAppointmentRepositoryMockRecorder) ListByPeriodAndUser(userID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPeriod", reflect.TypeOf((*MockAppointmentRepository)(nil).ListByPeriod), userID, start, end)
}

// Update mocks base method.
func (m *MockAppointmentRepository) Update(ap models.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAppointmentRepositoryMockRecorder) Update(ap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAppointmentRepository)(nil).Update), ap)
}
