// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\vinicius\Documents\Projetos\cabeleleila_leila\internal\service\service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/ViniciusBoroto/cabeleleila_leila/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAppointmentService is a mock of AppointmentService interface.
type MockAppointmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentServiceMockRecorder
}

// MockAppointmentServiceMockRecorder is the mock recorder for MockAppointmentService.
type MockAppointmentServiceMockRecorder struct {
	mock *MockAppointmentService
}

// NewMockAppointmentService creates a new mock instance.
func NewMockAppointmentService(ctrl *gomock.Controller) *MockAppointmentService {
	mock := &MockAppointmentService{ctrl: ctrl}
	mock.recorder = &MockAppointmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentService) EXPECT() *MockAppointmentServiceMockRecorder {
	return m.recorder
}

// ConfirmAppointment mocks base method.
func (m *MockAppointmentService) ConfirmAppointment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAppointment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmAppointment indicates an expected call of ConfirmAppointment.
func (mr *MockAppointmentServiceMockRecorder) ConfirmAppointment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAppointment", reflect.TypeOf((*MockAppointmentService)(nil).ConfirmAppointment), ctx, id)
}

// CreateAppointment mocks base method.
func (m *MockAppointmentService) CreateAppointment(ctx context.Context, a *models.Appointment) (*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", ctx, a)
	ret0, _ := ret[0].(*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockAppointmentServiceMockRecorder) CreateAppointment(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockAppointmentService)(nil).CreateAppointment), ctx, a)
}

// GetAppointment mocks base method.
func (m *MockAppointmentService) GetAppointment(ctx context.Context, id string) (*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointment", ctx, id)
	ret0, _ := ret[0].(*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointment indicates an expected call of GetAppointment.
func (mr *MockAppointmentServiceMockRecorder) GetAppointment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointment", reflect.TypeOf((*MockAppointmentService)(nil).GetAppointment), ctx, id)
}

// ListAppointments mocks base method.
func (m *MockAppointmentService) ListAppointments(ctx context.Context, from, to time.Time) ([]*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAppointments", ctx, from, to)
	ret0, _ := ret[0].([]*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAppointments indicates an expected call of ListAppointments.
func (mr *MockAppointmentServiceMockRecorder) ListAppointments(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAppointments", reflect.TypeOf((*MockAppointmentService)(nil).ListAppointments), ctx, from, to)
}

// ListIncoming mocks base method.
func (m *MockAppointmentService) ListIncoming(ctx context.Context) ([]*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncoming", ctx)
	ret0, _ := ret[0].([]*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncoming indicates an expected call of ListIncoming.
func (mr *MockAppointmentServiceMockRecorder) ListIncoming(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncoming", reflect.TypeOf((*MockAppointmentService)(nil).ListIncoming), ctx)
}

// SuggestSameWeekDate mocks base method.
func (m *MockAppointmentService) SuggestSameWeekDate(ctx context.Context, clientID string, weekOf time.Time) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestSameWeekDate", ctx, clientID, weekOf)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestSameWeekDate indicates an expected call of SuggestSameWeekDate.
func (mr *MockAppointmentServiceMockRecorder) SuggestSameWeekDate(ctx, clientID, weekOf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestSameWeekDate", reflect.TypeOf((*MockAppointmentService)(nil).SuggestSameWeekDate), ctx, clientID, weekOf)
}

// UpdateAppointment mocks base method.
func (m *MockAppointmentService) UpdateAppointment(ctx context.Context, id string, a *models.Appointment) (*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", ctx, id, a)
	ret0, _ := ret[0].(*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockAppointmentServiceMockRecorder) UpdateAppointment(ctx, id, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockAppointmentService)(nil).UpdateAppointment), ctx, id, a)
}

// UpdateServiceStatus mocks base method.
func (m *MockAppointmentService) UpdateServiceStatus(ctx context.Context, appointmentID, serviceID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceStatus", ctx, appointmentID, serviceID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceStatus indicates an expected call of UpdateServiceStatus.
func (mr *MockAppointmentServiceMockRecorder) UpdateServiceStatus(ctx, appointmentID, serviceID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceStatus", reflect.TypeOf((*MockAppointmentService)(nil).UpdateServiceStatus), ctx, appointmentID, serviceID, status)
}

// WeeklyPerformance mocks base method.
func (m *MockAppointmentService) WeeklyPerformance(ctx context.Context, weekStart time.Time) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WeeklyPerformance", ctx, weekStart)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WeeklyPerformance indicates an expected call of WeeklyPerformance.
func (mr *MockAppointmentServiceMockRecorder) WeeklyPerformance(ctx, weekStart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WeeklyPerformance", reflect.TypeOf((*MockAppointmentService)(nil).WeeklyPerformance), ctx, weekStart)
}
